ai_configuration = {
MINIMUM_MONEY_STOCKPILE = 5,
DIP_PEACE_DELAY = 7,
LEADERSHIP_TO_INFLUENCE = 0.15,
MINIMUM_SUPPLY_STOCKPILE = 20,
DIP_WAR_DELAY = 5,
USE_RESEARCH_MOD = 1,
USE_CUSTOM_TRIGGERS = 0,
MINIMUM_STOCKPILE = 50,
COUNTER_INFLUENCE = 1,
MINIMUM_IC_TO_INFLUENCE = 20,
INTELLIGENCE_DELAY = 7,
TRADE_DELAY = 5,
POLITICS_DELAY = 7
}
