ai_configuration = {
DIP_PEACE_DELAY = 14,
DIP_WAR_DELAY = 7,
POLITICS_DELAY = 7,
TRADE_DELAY = 0,
INTELLIGENCE_DELAY = 7,
STOCKPILE_FACTOR = 50,
LEAaDERSHIP_TO_INFLUENCE = 0.15,
MINIMUM_IC_TO_INFLUENCE = 20,
COUNTER_INFLUENCE = 1,
USE_CUSTOM_TRIGGERS = 0
}