ai_configuration = {
MINIMUM_MONEY_STOCKPILE = 5,
DIP_PEACE_DELAY = 15, --15
LEADERSHIP_TO_INFLUENCE = 0.15,
MINIMUM_SUPPLY_STOCKPILE = 20,
DIP_WAR_DELAY = 5, --5
USE_RESEARCH_MOD = 1,
USE_CUSTOM_TRIGGERS = 0,
MINIMUM_STOCKPILE = 50,
COUNTER_INFLUENCE = 1,
MINIMUM_IC_TO_INFLUENCE = 20,
INTELLIGENCE_DELAY = 7, --7
TRADE_DELAY = 7, -- 15
POLITICS_DELAY = 7, --7

G_MAX_GC_OVER_PRODUCTION = 15, -- How much IC are allowed to put into CG in %
TRADING_THRESHOLD = 0.5,
TRADING_CANCEL_THRESHOLD = 0.85,
G_MEASURED_TIME_PERIOD = 8, -- For how many days are we accounting for
G_AVERAGING_TIME_PERIOD = 7 -- How many days are averaged (must be < G_MEASURED_TIME_PERIOD)
}
