require('hoi3.Hoi3Object')

CModifierObject = Hoi3Object:subclass('hoi3.CModifier')

CModifierObject._MODIFIER_AIR_CAPACITY_	= 1
CModifierObject._MODIFIER_AIR_ORGANISATION_	= 2
CModifierObject._MODIFIER_ALIGN_TOWARDS_	= 3
CModifierObject._MODIFIER_ATTACK_REINFORCE_CHANCE_	= 4
CModifierObject._MODIFIER_ATTRITION_	= 5
CModifierObject._MODIFIER_COASTAL_FORT_LEVEL_	= 6
CModifierObject._MODIFIER_COMBAT_MOVEMENT_SPEED_	= 7
CModifierObject._MODIFIER_COMBAT_WIDTH_	= 8
CModifierObject._MODIFIER_COUNTER_ESPIONAGE_	= 9
CModifierObject._MODIFIER_COUNTER_INTELLIGENCE_	= 10
CModifierObject._MODIFIER_DEFEND_REINFORCE_CHANCE_	= 11
CModifierObject._MODIFIER_DISSENT_	= 12
CModifierObject._MODIFIER_DRIFT_SPEED_	= 13
CModifierObject._MODIFIER_ESPIONAGE_BONUS_	= 14
CModifierObject._MODIFIER_FORT_LEVEL_	= 15
CModifierObject._MODIFIER_GLOBAL_CRUDE_OIL_	= 16
CModifierObject._MODIFIER_GLOBAL_ENERGY_	= 17
CModifierObject._MODIFIER_GLOBAL_FUEL_	= 18
CModifierObject._MODIFIER_GLOBAL_IC_	= 19
CModifierObject._MODIFIER_GLOBAL_INFRASTRUCTURE_	= 20
CModifierObject._MODIFIER_GLOBAL_LEADERSHIP_	= 21
CModifierObject._MODIFIER_GLOBAL_LEADERSHIP_MODIFIER_	= 22
CModifierObject._MODIFIER_GLOBAL_MANPOWER_	= 23
CModifierObject._MODIFIER_GLOBAL_MANPOWER_MODIFIER_	= 24
CModifierObject._MODIFIER_GLOBAL_METAL_	= 25
CModifierObject._MODIFIER_GLOBAL_MONEY_	= 26
CModifierObject._MODIFIER_GLOBAL_RARE_MATERIALS_	= 27
CModifierObject._MODIFIER_GLOBAL_REVOLT_RISK_	= 28
CModifierObject._MODIFIER_GLOBAL_SUPPLIES_	= 29
CModifierObject._MODIFIER_IC_	= 30
CModifierObject._MODIFIER_INCORPORATE_COST_	= 31
CModifierObject._MODIFIER_INDUSTRIAL_EFFICIENCY_	= 32
CModifierObject._MODIFIER_INFRASTRUCTURE_	= 33
CModifierObject._MODIFIER_LAND_ORGANISATION_	= 34
CModifierObject._MODIFIER_LOCAL_ANTI_AIR_	= 35
CModifierObject._MODIFIER_LOCAL_CRUDE_OIL_	= 36
CModifierObject._MODIFIER_LOCAL_ENERGY_	= 37
CModifierObject._MODIFIER_LOCAL_FUEL_	= 38
CModifierObject._MODIFIER_LOCAL_IC_	= 39
CModifierObject._MODIFIER_LOCAL_INFRASTRUCTURE_	= 40
CModifierObject._MODIFIER_LOCAL_LEADERSHIP_	= 41
CModifierObject._MODIFIER_LOCAL_LEADERSHIP_MODIFIER_	= 42
CModifierObject._MODIFIER_LOCAL_MANPOWER_	= 43
CModifierObject._MODIFIER_LOCAL_MANPOWER_MODIFIER_	= 44
CModifierObject._MODIFIER_LOCAL_METAL_	= 45
CModifierObject._MODIFIER_LOCAL_MONEY_	= 46
CModifierObject._MODIFIER_LOCAL_PARTISAN_SUPPORT_	= 47
CModifierObject._MODIFIER_LOCAL_RARE_MATERIALS_	= 48
CModifierObject._MODIFIER_LOCAL_REVOLT_RISK_	= 49
CModifierObject._MODIFIER_LOCAL_SUPPLIES_	= 50
CModifierObject._MODIFIER_MAX_WAR_EXHAUSTION_	= 51
CModifierObject._MODIFIER_MINIMUM_REVOLT_RISK_	= 52
CModifierObject._MODIFIER_NATIONAL_UNITY_	= 53
CModifierObject._MODIFIER_NATIONAL_UNITY_EFFECT_	= 54
CModifierObject._MODIFIER_NAVAL_BASE_EFFICIENCY_	= 55
CModifierObject._MODIFIER_NAVAL_CAPACITY_	= 56
CModifierObject._MODIFIER_NAVAL_ORGANISATION_	= 57
CModifierObject._MODIFIER_NEUTRALITY_CHANGE_	= 58
CModifierObject._MODIFIER_OFFICER_RECRUITMENT_	= 59
CModifierObject._MODIFIER_OFFMAP_INDUSTRY_INTEL_	= 60
CModifierObject._MODIFIER_OFFMAP_LAND_INTEL_	= 61
CModifierObject._MODIFIER_OFFMAP_NAVAL_INTEL_	= 62
CModifierObject._MODIFIER_OFFMAP_POLITICAL_INTEL_	= 63
CModifierObject._MODIFIER_ORG_REGAIN_	= 64
CModifierObject._MODIFIER_PARTISAN_EFFICENCY_	= 65
CModifierObject._MODIFIER_PEACE_CONSUMER_GOODS_DEMAND_	= 66
CModifierObject._MODIFIER_PEACE_OFFMAP_INTEL_	= 67
CModifierObject._MODIFIER_PEACETIME_MANPOWER_ROTATION_	= 68
CModifierObject._MODIFIER_RADAR_LEVEL_	=69
CModifierObject._MODIFIER_RESEARCH_EFFICIENCY_	= 70
CModifierObject._MODIFIER_RESERVES_PENALTY_SIZE_	= 71
CModifierObject._MODIFIER_RULING_PARTY_SUPPORT_	= 72
CModifierObject._MODIFIER_SUPPLY_CONSUMPTION_	= 73
CModifierObject._MODIFIER_SUPPLY_THROUGHPUT_	= 74
CModifierObject._MODIFIER_SUSEPTIBILITY_	= 75
CModifierObject._MODIFIER_TERRITORIAL_PRIDE_	= 76
CModifierObject._MODIFIER_THREAT_IMPACT_	= 77
CModifierObject._MODIFIER_UNIT_RECRUITMENT_TIME_	= 78
CModifierObject._MODIFIER_UNIT_REPAIR_	= 79
CModifierObject._MODIFIER_UNIT_START_EXPERIENCE_	= 80
CModifierObject._MODIFIER_WAR_CONSUMER_GOODS_DEMAND_	= 81
CModifierObject._MODIFIER_WAR_EXHAUSTION_	= 82

---
-- @since 2.0
-- @static
-- @param number modifier
-- @return number
function CMinisterObject.GetValue(modifier)
	Hoi3Object.assertParameterType(1, modifier, 'number')
	
	Hoi3Object.throwNotYetImplemented()
end


-- CModifier has static methods and properties
-- we need to declare a CModifier table
CModifier = CModifierObject