require('hoi3')

module("hoi3.api", package.seeall)

CModifier = hoi3.AbstractObject:subclass('hoi3.CModifier')

CModifier._MODIFIER_AIR_CAPACITY_	= 1
CModifier._MODIFIER_AIR_ORGANISATION_	= 2
CModifier._MODIFIER_ALIGN_TOWARDS_	= 3
CModifier._MODIFIER_ATTACK_REINFORCE_CHANCE_	= 4
CModifier._MODIFIER_ATTRITION_	= 5
CModifier._MODIFIER_COASTAL_FORT_LEVEL_	= 6
CModifier._MODIFIER_COMBAT_MOVEMENT_SPEED_	= 7
CModifier._MODIFIER_COMBAT_WIDTH_	= 8
CModifier._MODIFIER_COUNTER_ESPIONAGE_	= 9
CModifier._MODIFIER_COUNTER_INTELLIGENCE_	= 10
CModifier._MODIFIER_DEFEND_REINFORCE_CHANCE_	= 11
CModifier._MODIFIER_DISSENT_	= 12
CModifier._MODIFIER_DRIFT_SPEED_	= 13
CModifier._MODIFIER_ESPIONAGE_BONUS_	= 14
CModifier._MODIFIER_FORT_LEVEL_	= 15
CModifier._MODIFIER_GLOBAL_CRUDE_OIL_	= 16
CModifier._MODIFIER_GLOBAL_ENERGY_	= 17
CModifier._MODIFIER_GLOBAL_FUEL_	= 18
CModifier._MODIFIER_GLOBAL_IC_	= 19
CModifier._MODIFIER_GLOBAL_INFRASTRUCTURE_	= 20
CModifier._MODIFIER_GLOBAL_LEADERSHIP_	= 21
CModifier._MODIFIER_GLOBAL_LEADERSHIP_MODIFIER_	= 22
CModifier._MODIFIER_GLOBAL_MANPOWER_	= 23
CModifier._MODIFIER_GLOBAL_MANPOWER_MODIFIER_	= 24
CModifier._MODIFIER_GLOBAL_METAL_	= 25
CModifier._MODIFIER_GLOBAL_MONEY_	= 26
CModifier._MODIFIER_GLOBAL_RARE_MATERIALS_	= 27
CModifier._MODIFIER_GLOBAL_REVOLT_RISK_	= 28
CModifier._MODIFIER_GLOBAL_SUPPLIES_	= 29
CModifier._MODIFIER_IC_	= 30
CModifier._MODIFIER_INCORPORATE_COST_	= 31
CModifier._MODIFIER_INDUSTRIAL_EFFICIENCY_	= 32
CModifier._MODIFIER_INFRASTRUCTURE_	= 33
CModifier._MODIFIER_LAND_ORGANISATION_	= 34
CModifier._MODIFIER_LOCAL_ANTI_AIR_	= 35
CModifier._MODIFIER_LOCAL_CRUDE_OIL_	= 36
CModifier._MODIFIER_LOCAL_ENERGY_	= 37
CModifier._MODIFIER_LOCAL_FUEL_	= 38
CModifier._MODIFIER_LOCAL_IC_	= 39
CModifier._MODIFIER_LOCAL_INFRASTRUCTURE_	= 40
CModifier._MODIFIER_LOCAL_LEADERSHIP_	= 41
CModifier._MODIFIER_LOCAL_LEADERSHIP_MODIFIER_	= 42
CModifier._MODIFIER_LOCAL_MANPOWER_	= 43
CModifier._MODIFIER_LOCAL_MANPOWER_MODIFIER_	= 44
CModifier._MODIFIER_LOCAL_METAL_	= 45
CModifier._MODIFIER_LOCAL_MONEY_	= 46
CModifier._MODIFIER_LOCAL_PARTISAN_SUPPORT_	= 47
CModifier._MODIFIER_LOCAL_RARE_MATERIALS_	= 48
CModifier._MODIFIER_LOCAL_REVOLT_RISK_	= 49
CModifier._MODIFIER_LOCAL_SUPPLIES_	= 50
CModifier._MODIFIER_MAX_WAR_EXHAUSTION_	= 51
CModifier._MODIFIER_MINIMUM_REVOLT_RISK_	= 52
CModifier._MODIFIER_NATIONAL_UNITY_	= 53
CModifier._MODIFIER_NATIONAL_UNITY_EFFECT_	= 54
CModifier._MODIFIER_NAVAL_BASE_EFFICIENCY_	= 55
CModifier._MODIFIER_NAVAL_CAPACITY_	= 56
CModifier._MODIFIER_NAVAL_ORGANISATION_	= 57
CModifier._MODIFIER_NEUTRALITY_CHANGE_	= 58
CModifier._MODIFIER_OFFICER_RECRUITMENT_	= 59
CModifier._MODIFIER_OFFMAP_INDUSTRY_INTEL_	= 60
CModifier._MODIFIER_OFFMAP_LAND_INTEL_	= 61
CModifier._MODIFIER_OFFMAP_NAVAL_INTEL_	= 62
CModifier._MODIFIER_OFFMAP_POLITICAL_INTEL_	= 63
CModifier._MODIFIER_ORG_REGAIN_	= 64
CModifier._MODIFIER_PARTISAN_EFFICENCY_	= 65
CModifier._MODIFIER_PEACE_CONSUMER_GOODS_DEMAND_	= 66
CModifier._MODIFIER_PEACE_OFFMAP_INTEL_	= 67
CModifier._MODIFIER_PEACETIME_MANPOWER_ROTATION_	= 68
CModifier._MODIFIER_RADAR_LEVEL_	=69
CModifier._MODIFIER_RESEARCH_EFFICIENCY_	= 70
CModifier._MODIFIER_RESERVES_PENALTY_SIZE_	= 71
CModifier._MODIFIER_RULING_PARTY_SUPPORT_	= 72
CModifier._MODIFIER_SUPPLY_CONSUMPTION_	= 73
CModifier._MODIFIER_SUPPLY_THROUGHPUT_	= 74
CModifier._MODIFIER_SUSEPTIBILITY_	= 75
CModifier._MODIFIER_TERRITORIAL_PRIDE_	= 76
CModifier._MODIFIER_THREAT_IMPACT_	= 77
CModifier._MODIFIER_UNIT_RECRUITMENT_TIME_	= 78
CModifier._MODIFIER_UNIT_REPAIR_	= 79
CModifier._MODIFIER_UNIT_START_EXPERIENCE_	= 80
CModifier._MODIFIER_WAR_CONSUMER_GOODS_DEMAND_	= 81
CModifier._MODIFIER_WAR_EXHAUSTION_	= 82

---
-- @since 2.0
-- @param number modifier
-- @return number
function CModifier:GetValue(modifier)
	hoi3.assertParameterType(1, modifier, 'number')
	
	hoi3.throwNotYetImplemented()
end